# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  cloud {
    hostname     = "app.terraform.io"
    organization = "homelab_hudater"

    workspaces {
      name = "OCI-zurich"
    }
  }
}
