#!/usr/bin/env bash
# gen-inventory.sh
# Generates ansible/inventory/hosts.ini from `tofu output`
# Run from project root after: cd terraform && tofu apply
# TODO: handoff from tf

set -euo pipefail

TF_DIR="$(dirname "$0")/terraform"
INV_FILE="$(dirname "$0")/ansible/inventory/hosts.ini"

echo "Reading Terraform outputs from $TF_DIR ..."
cd "$TF_DIR"

SERVER_IPS=$(tofu output -json server_ips | jq -r 'to_entries[] | "\(.key) \(.value)"' | sed 's|/[0-9]*||')
AGENT_IPS=$(tofu output -json agent_ips   | jq -r 'to_entries[] | "\(.key) \(.value)"' | sed 's|/[0-9]*||')

cat > "$INV_FILE" << EOF
# Auto-generated by gen-inventory.sh — do not edit manually
# Regenerate with: bash gen-inventory.sh

[k3s_servers]
$(echo "$SERVER_IPS" | awk 'NR==1{print $1 " ansible_host=" $2 " k3s_init_node=true"} NR>1{print $1 " ansible_host=" $2}')

[k3s_agents]
$(echo "$AGENT_IPS" | awk '{print $1 " ansible_host=" $2}')

[k3s_cluster:children]
k3s_servers
k3s_agents

[k3s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
EOF

echo "Written: $INV_FILE"
cat "$INV_FILE"
